ALTER TABLE "songs" DROP COLUMN IF EXISTS "coverUrl";
ALTER TABLE "songs" DROP COLUMN IF EXISTS "demoUrl";
ALTER TABLE "songs" DROP COLUMN IF EXISTS "fullUrl";
ALTER TABLE "songs" ADD COLUMN IF NOT EXISTS "coverImage" BYTEA;
ALTER TABLE "songs" ADD COLUMN IF NOT EXISTS "coverMimeType" TEXT;
ALTER TABLE "songs" ADD COLUMN IF NOT EXISTS "demoAudio" BYTEA;
ALTER TABLE "songs" ADD COLUMN IF NOT EXISTS "demoMimeType" TEXT;
ALTER TABLE "songs" ADD COLUMN IF NOT EXISTS "fullAudio" BYTEA;
ALTER TABLE "songs" ADD COLUMN IF NOT EXISTS "fullMimeType" TEXT;
